import { LegacyScreenSpec } from '../contracts/legacy-contracts';
import { LEGACY_SCREEN_DEPENDENCY_REGISTRY } from '../registry/screen-dependency.registry';

export const LEGACY_SCREEN_SPECS: Record<string, LegacyScreenSpec> = {
  TREE: {
    code: 'TREE',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['TREE'],
    shortcuts: ['F2', 'F3', 'F4', 'F6', 'F7', 'F8', 'F10', 'Escape'],
    requiredActions: ['new', 'save', 'edit', 'delete', 'search', 'print', 'props', 'exit', 'cancel'],
    acceptanceChecklist: [
      'Visual parity: tree, header selectors, toolbar, audit footer.',
      'Functional parity: hierarchy expand/collapse, SNF grid behavior, F-keys.',
      'Dependency pass: TREE tables + report coverage through API and UI.',
      'Source pass: compare against catalog sourceMeta and legacyKeys.',
    ],
  },
  SNDS: {
    code: 'SNDS',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['SNDS'],
    shortcuts: ['F2', 'F3', 'F4', 'F6', 'F7', 'F8', 'F10', 'Escape'],
    requiredActions: ['new', 'save', 'edit', 'delete', 'search', 'print', 'post', 'unpost', 'add-line', 'exit'],
    acceptanceChecklist: [
      'Visual parity: voucher header, detail grid, toolbar, status, audit.',
      'Functional parity: CRUD + post/unpost + LOV + print.',
      'Dependency pass: SNDS dependencies and called forms mapped.',
      'Source pass: compare against catalog sourceMeta and legacyKeys.',
    ],
  },
  SNDK: {
    code: 'SNDK',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['SNDK'],
    shortcuts: ['F2', 'F3', 'F4', 'F6', 'F7', 'F8', 'F10', 'Escape'],
    requiredActions: ['new', 'save', 'edit', 'delete', 'search', 'print', 'post', 'unpost', 'add-line', 'exit'],
    acceptanceChecklist: [
      'Visual parity: receipt voucher chrome and control layout.',
      'Functional parity: CRUD + post/unpost + LOV + print.',
      'Dependency pass: SNDK dependencies and called forms mapped.',
      'Source pass: compare against catalog sourceMeta and legacyKeys.',
    ],
  },
  SNDKD: {
    code: 'SNDKD',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['SNDKD'],
    shortcuts: ['F2', 'F3', 'F4', 'F6', 'F7', 'F8', 'F10', 'Escape'],
    requiredActions: ['new', 'save', 'edit', 'delete', 'search', 'print', 'post', 'unpost', 'refresh', 'export', 'exit'],
    acceptanceChecklist: [
      'Visual parity: daily journal header/detail/footer and toolbar.',
      'Functional parity: balance validation, post/unpost, search modal, print.',
      'Dependency pass: SNDKD dependencies and endpoints covered.',
      'Source pass: compare against catalog sourceMeta and legacyKeys.',
    ],
  },
  SNDKD2: {
    code: 'SNDKD2',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['SNDKD2'],
    shortcuts: ['F2', 'F3', 'F4', 'F6', 'F7', 'F8', 'F10', 'Escape'],
    requiredActions: ['new', 'save', 'edit', 'delete', 'search', 'print', 'post', 'unpost', 'refresh', 'exit'],
    acceptanceChecklist: [
      'Visual parity: transfer debit/credit panels with legacy chrome.',
      'Functional parity: transfer balancing + currency/rate logic + post flow.',
      'Dependency pass: SNDKD2 dependencies and endpoints covered.',
      'Source pass: compare against catalog sourceMeta and legacyKeys.',
    ],
  },
  SYSALL: {
    code: 'SYSALL',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['SYSALL'],
    shortcuts: ['F2', 'F3', 'F4', 'F6', 'F7', 'F8', 'F10', 'Escape'],
    requiredActions: ['save', 'edit', 'search', 'cancel', 'exit'],
    acceptanceChecklist: [
      'Visual parity: settings groups, checkboxes, and legacy save flow.',
      'Functional parity: TITL/SCR settings save without changing old source.',
      'Dependency pass: SYSALL dependencies and endpoints covered.',
      'Source pass: compare against catalog sourceMeta and legacyKeys.',
    ],
  },
  REPKHALL: {
    code: 'REPKHALL',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPKHALL'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPKHR: {
    code: 'REPKHR',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPKHR'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPKHHR: {
    code: 'REPKHHR',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPKHHR'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPKHALLR: {
    code: 'REPKHALLR',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPKHALLR'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPSNDOK: {
    code: 'REPSNDOK',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPSNDOK'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  MSDKA: {
    code: 'MSDKA',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['MSDKA'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  DATA_AM: {
    code: 'DATA_AM',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['DATA_AM'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  DATA_MO: {
    code: 'DATA_MO',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['DATA_MO'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  USER: {
    code: 'USER',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['USER'],
    shortcuts: [
      'Escape',
      'F8',
    ],
    requiredActions: [
      'edit',
      'exit',
      'print',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  DATA_AML: {
    code: 'DATA_AML',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['DATA_AML'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  RSEDIF: {
    code: 'RSEDIF',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['RSEDIF'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  MRT: {
    code: 'MRT',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['MRT'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  AHTSAR: {
    code: 'AHTSAR',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['AHTSAR'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F8',
    ],
    requiredActions: [
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  COPY: {
    code: 'COPY',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['COPY'],
    shortcuts: [
      'Escape',
      'F10',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  INANOU: {
    code: 'INANOU',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['INANOU'],
    shortcuts: [
      'Escape',
    ],
    requiredActions: [
      'edit',
      'exit',
      'print',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  TRHL: {
    code: 'TRHL',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['TRHL'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  TEL: {
    code: 'TEL',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['TEL'],
    shortcuts: [
      'Escape',
      'F10',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  AKFAL: {
    code: 'AKFAL',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['AKFAL'],
    shortcuts: [
      'Escape',
      'F10',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  KF: {
    code: 'KF',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['KF'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F8',
    ],
    requiredActions: [
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  SMS: {
    code: 'SMS',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['SMS'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  SMSN: {
    code: 'SMSN',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['SMSN'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  SYS_SMS: {
    code: 'SYS_SMS',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['SYS_SMS'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  MEMO: {
    code: 'MEMO',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['MEMO'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F8',
    ],
    requiredActions: [
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  AKFA: {
    code: 'AKFA',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['AKFA'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'post',
      'print',
      'save',
      'search',
      'unpost',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPSK: {
    code: 'REPSK',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPSK'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPSS: {
    code: 'REPSS',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPSS'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPKD: {
    code: 'REPKD',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPKD'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPKD2: {
    code: 'REPKD2',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPKD2'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPDAY: {
    code: 'REPDAY',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPDAY'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPMZN: {
    code: 'REPMZN',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPMZN'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPRANDH: {
    code: 'REPRANDH',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPRANDH'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPMZNYH: {
    code: 'REPMZNYH',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPMZNYH'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
  REPMEMO: {
    code: 'REPMEMO',
    dependencies: LEGACY_SCREEN_DEPENDENCY_REGISTRY['REPMEMO'],
    shortcuts: [
      'Escape',
      'F10',
      'F2',
      'F6',
      'F8',
    ],
    requiredActions: [
      'delete',
      'edit',
      'exit',
      'new',
      'print',
      'save',
      'search',
    ],
    acceptanceChecklist: [
      'Visual pass: legacy window, toolbar, grid, status, and labels match the old live screen.',
      'Functional pass: CRUD/search/print/LOV/keyboard behavior match source triggers.',
      'Dependency pass: tables, called forms, reports, routines, and LOVs are covered.',
      'Source pass: compare against catalog sourceMeta and old live behavior.',
    ],
  },
};
