import { LegacyScreenDependency } from '../contracts/legacy-contracts';

const SOURCE_CATALOG = 'D:/daty/_legacy_source_catalog_20260424_full';

export const LEGACY_SCREEN_DEPENDENCY_REGISTRY: Record<string, LegacyScreenDependency> = {
  TREE: {
    baseTable: 'DATA_AC',
    tables: [
      'AMHSB', 'ATMMY', 'ATMY', 'DATAK', 'DATAK_SLF', 'DATAK_Y', 'DATA_AC',
      'DATA_ACM', 'DATA_BL', 'DATA_BR1', 'FBMY', 'FBVF_Y', 'FBY', 'FMMY',
      'FMVFT_Y', 'FMVF_Y', 'FMY', 'HWM', 'MSHRI', 'MSHRI2', 'MZT', 'SWDAR',
      'TITL', 'USERGN', 'USER_U',
    ],
    calledForms: [],
    reports: ['EXD'],
    dbRoutines: ['NAME_HSB'],
    lovs: ['NA2'],
    legacyKeys: [
      'KEY-CLRBLK', 'KEY-CLRFRM', 'KEY-CLRREC', 'KEY-COMMIT', 'KEY-CQUERY',
      'KEY-CREREC', 'KEY-DELREC', 'KEY-DOWN', 'KEY-DUP-ITEM', 'KEY-DUPREC',
      'KEY-ENTQRY', 'KEY-EXEQRY', 'KEY-EXIT', 'KEY-HELP', 'KEY-MENU',
      'KEY-NEXT-ITEM', 'KEY-UP',
    ],
    coverageApi: [
      '/api/titl',
      '/api/me',
      '/api/accounts/tree',
      '/api/lov/NA2',
      '/api/accounts/:noa',
      '/api/accounts/:noa/balances',
      '/api/accounts/:noa/snf',
      '/api/accounts',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/TREE/screen.json`,
      sourcePath: 'form/TREE.fmb',
      sourceSha256: '1ef9023befc7657a2a5c0ba031aaa29b7fde8d545ebc3e74862a7873513f1d48',
      lineCount: 10089,
      uniqueTriggerCount: 41,
      rawTriggerHits: 328,
      programUnitCount: 16,
    },
  },
  SNDS: {
    baseTable: 'SNDS',
    tables: [
      'AHTSR', 'AKFA', 'AMHSB', 'AMLH', 'DATAK', 'DATA_AC', 'DATA_ACM',
      'HMHALL', 'KDAY', 'MONTH', 'MRT', 'MSHRI2', 'SNDK', 'SNDKF', 'SNDK_T',
      'SNDS', 'SNDSF', 'TITL', 'USERGN', 'USER_U', 'YEAR',
    ],
    calledForms: ['REPKHALL', 'REPSS', 'TREE'],
    reports: ['SNDS', 'SNDS2', 'SNDS3', 'SNDSK'],
    dbRoutines: ['CAMLH', 'INDATE', 'MORNOM', 'NAME_MRT', 'RSED_SMS', 'SQUNX', 'TOCHAR'],
    lovs: ['MEMO', 'MEMO2', 'MRT', 'MRT2', 'NA2', 'NAM', 'NAS'],
    legacyKeys: [
      'KEY-CLRBLK', 'KEY-CLRFRM', 'KEY-CLRREC', 'KEY-COMMIT', 'KEY-CQUERY',
      'KEY-CREREC', 'KEY-DELREC', 'KEY-DOWN', 'KEY-DUP-ITEM', 'KEY-DUPREC',
      'KEY-ENTQRY', 'KEY-EXEQRY', 'KEY-EXIT', 'KEY-HELP', 'KEY-LISTVAL',
      'KEY-MENU', 'KEY-NEXT-ITEM', 'KEY-UP',
    ],
    coverageApi: [
      '/api/data/SNDS',
      '/api/voucher/snds',
      '/api/voucher/snds/post',
      '/api/voucher/snds/unpost',
      '/api/voucher/snds/print',
      '/api/lov/MEMO',
      '/api/lov/MEMO2',
      '/api/lov/MRT',
      '/api/lov/MRT2',
      '/api/lov/NA2',
      '/api/lov/NAM',
      '/api/lov/NAS',
      '/api/lov/accounts',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/SNDS/screen.json`,
      sourcePath: 'form/snds.fmb',
      sourceSha256: 'd9e0a6f089aaee48614b59f0c7045770b80ca3f3e281472fefb4c25fbc586b7b',
      lineCount: 19593,
      uniqueTriggerCount: 43,
      rawTriggerHits: 422,
      programUnitCount: 36,
    },
  },
  SNDK: {
    baseTable: 'SNDK',
    tables: [
      'AHTSR', 'AKFA', 'AMHSB', 'AMLH', 'DATAK', 'DATA_AC', 'DATA_ACM',
      'HMHALL', 'KDAY', 'MONTH', 'MRT', 'MSHRI2', 'SNDK', 'SNDKF', 'SNDK_T',
      'TITL', 'USERGN', 'USER_U', 'YEAR',
    ],
    calledForms: ['REPKHALL', 'REPSK', 'TREE'],
    reports: ['SNDK'],
    dbRoutines: ['CAMLH', 'INDATE', 'MORNOM', 'NAME_MRT', 'RSED_SMS', 'SQUNX', 'TOCHAR'],
    lovs: ['MEMO', 'MEMO2', 'MRT', 'MRT2', 'NA2', 'NAM', 'NAS'],
    legacyKeys: [
      'KEY-CLRBLK', 'KEY-CLRFRM', 'KEY-CLRREC', 'KEY-COMMIT', 'KEY-CQUERY',
      'KEY-CREREC', 'KEY-DELREC', 'KEY-DOWN', 'KEY-DUP-ITEM', 'KEY-DUPREC',
      'KEY-ENTQRY', 'KEY-EXEQRY', 'KEY-EXIT', 'KEY-HELP', 'KEY-LISTVAL',
      'KEY-MENU', 'KEY-NEXT-ITEM', 'KEY-SCRDOWN', 'KEY-SCRUP', 'KEY-UP',
    ],
    coverageApi: [
      '/api/data/SNDK',
      '/api/voucher/sndk',
      '/api/voucher/sndk/post',
      '/api/voucher/sndk/unpost',
      '/api/voucher/sndk/print',
      '/api/lov/MEMO',
      '/api/lov/MEMO2',
      '/api/lov/MRT',
      '/api/lov/MRT2',
      '/api/lov/NA2',
      '/api/lov/NAM',
      '/api/lov/NAS',
      '/api/lov/accounts',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/SNDK/screen.json`,
      sourcePath: 'form/sndk.fmb',
      sourceSha256: '8cdb13c2fcbb8f1a9b85f8f78b131e827b8a34348523a680d8a860f6ce53ad3e',
      lineCount: 17128,
      uniqueTriggerCount: 44,
      rawTriggerHits: 520,
      programUnitCount: 38,
    },
  },
  SNDKD: {
    baseTable: 'SNDKD',
    tables: [
      'AHTSR', 'AKFA', 'AMHSB', 'AMLH', 'DASOKA', 'DASOKAM', 'DATAFSOKF',
      'DATAK', 'DATA_AC', 'DATA_ACM', 'HMHALL', 'KDAY', 'MONTH', 'MRT',
      'MSHRI2', 'SNDGAMD2', 'SNDGAMD3', 'SNDGAMD4', 'SNDKD', 'SNDKDF',
      'SNDSDAD', 'TITL', 'TITLX', 'USERGN', 'USER_U', 'YEAR',
    ],
    calledForms: ['REPKD', 'REPKHALL', 'TREE'],
    reports: ['SNDKD'],
    dbRoutines: ['CAMLH', 'INDATE', 'MORNOM', 'NAME_MRT', 'RSED_SMS', 'SQUNX', 'TOCHAR'],
    lovs: ['DORY', 'MEMO', 'MRT', 'MRT2', 'NA2'],
    legacyKeys: [
      'KEY-CLRBLK', 'KEY-CLRFRM', 'KEY-CLRREC', 'KEY-COMMIT', 'KEY-CQUERY',
      'KEY-CREREC', 'KEY-DELREC', 'KEY-DOWN', 'KEY-DUP-ITEM', 'KEY-DUPREC',
      'KEY-ENTQRY', 'KEY-EXEQRY', 'KEY-EXIT', 'KEY-HELP', 'KEY-LISTVAL',
      'KEY-MENU', 'KEY-NEXT-ITEM', 'KEY-UP',
    ],
    coverageApi: [
      '/api/titl',
      '/api/me',
      '/api/journal/sndkd/list',
      '/api/journal/sndkd',
      '/api/journal/sndkd/post',
      '/api/journal/sndkd/unpost',
      '/api/journal/sndkd/search',
      '/api/journal/sndkd/by-noson',
      '/api/journal/sndkd/print',
      '/api/lov/DORY',
      '/api/lov/MEMO',
      '/api/lov/MRT',
      '/api/lov/MRT2',
      '/api/lov/NA2',
      '/api/lov/accounts',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/SNDKD/screen.json`,
      sourcePath: 'form/sndkd.fmb',
      sourceSha256: 'f200920b3c924b39fa05d4359f9be08de779efe4aadfaa5dff989beb1957b1ad',
      lineCount: 15853,
      uniqueTriggerCount: 42,
      rawTriggerHits: 370,
      programUnitCount: 32,
    },
  },
  SNDKD2: {
    baseTable: 'SNDKD2',
    tables: [
      'AHTSR', 'AKFA', 'AMHSB', 'AMLH', 'DATAK', 'DATA_AC', 'DATA_ACM',
      'DATA_BR1', 'HMHALL', 'KDAY', 'MONTH', 'MRT', 'MSHRI2', 'SNDKD2',
      'TITL', 'USERGN', 'USER_U', 'YEAR',
    ],
    calledForms: ['REPKD2', 'REPKHALL'],
    reports: ['SNDKD2'],
    dbRoutines: ['CAMLH', 'INDATE', 'MORNOM', 'NAME_MRT', 'RSED_SMS', 'SQUNX', 'TOCHAR'],
    lovs: ['MEMO', 'MRT2', 'NA2', 'NA22', 'NAM', 'NAM2'],
    legacyKeys: [
      'KEY-CLRBLK', 'KEY-CLRFRM', 'KEY-CLRREC', 'KEY-COMMIT', 'KEY-CQUERY',
      'KEY-CREREC', 'KEY-DELREC', 'KEY-DOWN', 'KEY-DUP-ITEM', 'KEY-DUPREC',
      'KEY-ENTQRY', 'KEY-EXEQRY', 'KEY-EXIT', 'KEY-HELP', 'KEY-LISTVAL',
      'KEY-MENU', 'KEY-NEXT-ITEM', 'KEY-UP',
    ],
    coverageApi: [
      '/api/journal/sndkd2/list',
      '/api/journal/sndkd2',
      '/api/journal/sndkd2/post',
      '/api/journal/sndkd2/unpost',
      '/api/journal/sndkd2/search',
      '/api/journal/sndkd2/by-noson',
      '/api/journal/sndkd2/print',
      '/api/lov/MEMO',
      '/api/lov/MRT2',
      '/api/lov/NA2',
      '/api/lov/NA22',
      '/api/lov/NAM',
      '/api/lov/NAM2',
      '/api/lov/accounts',
      '/api/currencies',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/SNDKD2/screen.json`,
      sourcePath: 'form/sndkd2.fmb',
      sourceSha256: '50eafb2ba7d7019a47f27257ed3ae0f8f34f9e3705b6a5207abd1d44da959db9',
      lineCount: 13870,
      uniqueTriggerCount: 38,
      rawTriggerHits: 412,
      programUnitCount: 24,
    },
  },
  SYSALL: {
    baseTable: 'TITL',
    tables: ['AMHSB', 'DATA_AC', 'DATA_AG', 'SCR', 'TITL'],
    calledForms: [],
    reports: [],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
      'KEY-CLRBLK', 'KEY-CLRFRM', 'KEY-CLRREC', 'KEY-CQUERY', 'KEY-DELREC',
      'KEY-ENTQRY', 'KEY-EXEQRY', 'KEY-EXIT', 'KEY-HELP', 'KEY-MENU',
      'KEY-NEXT-ITEM', 'KEY-UP',
    ],
    coverageApi: [
      '/api/titl',
      '/api/data/SCR',
      '/api/data/DATA_AG',
      '/api/accounts/tree',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/SYSALL/screen.json`,
      sourcePath: 'form/sysall.fmb',
      sourceSha256: 'ccaa5c6c43a9f1cf1d40b765638a279bf4473ae9c40c286f64a400f8626815fe',
      lineCount: 6904,
      uniqueTriggerCount: 23,
      rawTriggerHits: 227,
      programUnitCount: 6,
    },
  },
  REPKHALL: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'AMLH',
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'DATA_BR1',
    'DA_SNF',
    'FB',
    'FBA',
    'FMD',
    'HMHALL',
    'MSHRIF',
    'SNDSDAD',
    'TITL',
    'TITLX',
    'TYPEMS',
    'USERGN',
  ],
    calledForms: [
    'REPKHALL2',
  ],
    reports: [
    'AR2',
    'DATAFSOKNN',
    'MSDKA',
    'PSNDASHS',
    'REPFDL',
    'REPFMX2',
    'REPFMX22',
    'REPKAMFS',
    'REPKAMFSSX2',
    'REPKGD',
    'REPKHRA',
    'REPKHRM',
    'REPSNDASH',
    'REPSNDASHR',
    'REPSNDASHS',
    'TYPEMS',
  ],
    dbRoutines: [
    'AL_RB_MS',
    'FREP',
    'RSEDSANDH',
  ],
    lovs: [
    'NA2',
    'NAM',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-LISTVAL',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPKHALL/screen.json`,
      sourcePath: 'form/repkhall.fmb',
      sourceSha256: '42f18cb55f4464abc3e354c8f73736adae2ed0897b983b7ada3ed799b3b3868f',
      lineCount: 10527,
      uniqueTriggerCount: 32,
      rawTriggerHits: 268,
      programUnitCount: 11,
    },
  },
  REPKHR: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'HMH',
    'MRT',
    'RKHR',
    'TITL',
    'USERGN',
  ],
    calledForms: [],
    reports: [
    'REPKHR2',
    'REPKHR21',
    'REPKHR22',
    'REPKHR221HS1',
    'REPKHR2221',
    'REPKHR2X',
    'TYPEMS',
  ],
    dbRoutines: [
    'CAMLH',
  ],
    lovs: [
    'NA2',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-LISTVAL',
    'KEY-MENU',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPKHR/screen.json`,
      sourcePath: 'form/REPKHR.fmb',
      sourceSha256: '47aa35dc5b6c3cc6417c4b9e8f5b96120d18486b4d0dfd079009627fd028c5f0',
      lineCount: 5282,
      uniqueTriggerCount: 28,
      rawTriggerHits: 150,
      programUnitCount: 6,
    },
  },
  REPKHHR: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'AMLH',
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'GRP',
    'HMH',
    'HMHALL',
    'MRT',
    'TITL',
    'USERGN',
  ],
    calledForms: [],
    reports: [
    'REPKH',
    'REPKH2',
    'REPKH3',
    'REPKH33',
    'REPKH3R',
    'REPKH4',
    'REPKH44',
    'REPKHDAY',
    'REPKHDAY1',
    'REPKHX',
    'TYPEMS',
  ],
    dbRoutines: [
    'CAMLH',
    'G_T_F',
    'NAME_HSB',
  ],
    lovs: [
    'NA2',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-LISTVAL',
    'KEY-NEXT-ITEM',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPKHHR/screen.json`,
      sourcePath: 'form/repkhhr.fmb',
      sourceSha256: 'fd3c3e73c1d00d95cff643ae69136e6e02e6130372ae477dd23b8a4eba4861c5',
      lineCount: 9434,
      uniqueTriggerCount: 31,
      rawTriggerHits: 260,
      programUnitCount: 8,
    },
  },
  REPKHALLR: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'AMLH',
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'DATA_ALL',
    'HMH',
    'MSHRIF',
    'RSIF',
    'TITL',
    'TYPEMS',
    'USERGN',
  ],
    calledForms: [],
    reports: [
    'TYPEMS',
  ],
    dbRoutines: [
    'FREP',
    'RSEDSANDH',
  ],
    lovs: [
    'NA2',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-LISTVAL',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPKHALLR/screen.json`,
      sourcePath: 'form/repkhallR.fmb',
      sourceSha256: 'd67886efd5bca540d191ecd2fb686a5b3b7d17111c1c06a6af63eef07d667a54',
      lineCount: 7828,
      uniqueTriggerCount: 33,
      rawTriggerHits: 202,
      programUnitCount: 20,
    },
  },
  REPSNDOK: {
    baseTable: 'AMLH',
    tables: [
    'AMLH',
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'HMH',
    'USERGN',
  ],
    calledForms: [],
    reports: [
    'REPSNDOK1',
    'REPSNDOKG',
  ],
    dbRoutines: [],
    lovs: [
    'NA2',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-LISTVAL',
    'KEY-MENU',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMLH',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPSNDOK/screen.json`,
      sourcePath: 'form/repsndok.fmb',
      sourceSha256: 'bc684243b36fa578f272e31022ad475dcf0e531cc507b7dc026da28eae4ac319',
      lineCount: 4053,
      uniqueTriggerCount: 28,
      rawTriggerHits: 155,
      programUnitCount: 4,
    },
  },
  MSDKA: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'ASMF',
    'ATMF',
    'ATMMF',
    'DATAK',
    'DATA_AC',
    'DATA_TM1',
    'FBMF',
    'FMF',
    'FMMF',
    'SMRF',
    'TGROM',
    'TGROMB',
    'TITL',
    'TITLX',
    'TMF',
  ],
    calledForms: [],
    reports: [
    'MSDKA',
  ],
    dbRoutines: [
    'NAME_GHSB',
    'RSEDSANDH',
  ],
    lovs: [
    'NA2',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/MSDKA/screen.json`,
      sourcePath: 'form/msdka.fmb',
      sourceSha256: '029841bf0aeeb7abc3666b7aa339e80bcada45cecfb182cd9c84fd3dc3d5591c',
      lineCount: 5008,
      uniqueTriggerCount: 32,
      rawTriggerHits: 135,
      programUnitCount: 6,
    },
  },
  DATA_AM: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'ATMMY',
    'ATMY',
    'DATAK',
    'DATAK_SLF',
    'DATAK_Y',
    'DATA_AC',
    'DATA_ACM',
    'DATA_BL',
    'FBMY',
    'FBVF_Y',
    'FBY',
    'FMMY',
    'FMVFT_Y',
    'FMVF_Y',
    'FMY',
    'GRP',
    'HWM',
    'MRT',
    'SAR_H',
    'SWDAR',
    'TITL',
    'USERGN',
    'USER_U',
  ],
    calledForms: [
    'GRP22',
    'SAR_H',
  ],
    reports: [
    'EXD2',
  ],
    dbRoutines: [
    'NAME_HSB',
    'NAME_MRT',
  ],
    lovs: [
    'G',
    'MRT2',
    'NA2',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-LISTVAL',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/DATA_AM/screen.json`,
      sourcePath: 'form/data_am.fmb',
      sourceSha256: '7effe2b415b2788391be0be9885d5e2d9ad0d8ab425f0ca11dd243a191b4feea',
      lineCount: 9689,
      uniqueTriggerCount: 39,
      rawTriggerHits: 208,
      programUnitCount: 17,
    },
  },
  DATA_MO: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'ATMMY',
    'ATMY',
    'DATAFSOK',
    'DATAK',
    'DATAK_SLF',
    'DATAK_Y',
    'DATA_AC',
    'DATA_ACM',
    'DATA_BL',
    'FBMY',
    'FBVF_Y',
    'FBY',
    'FMMY',
    'FMVFT_Y',
    'FMVF_Y',
    'FMY',
    'GRP',
    'HWM',
    'MNTKA',
    'SNDSDAD',
    'SNF',
    'TITL',
    'USERGN',
    'USER_U',
  ],
    calledForms: [
    'GRP',
    'MNTKA',
  ],
    reports: [
    'EXD3',
  ],
    dbRoutines: [],
    lovs: [
    'MNTKA',
    'NA2',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/DATA_MO/screen.json`,
      sourcePath: 'form/data_mo.fmb',
      sourceSha256: 'c3861cc180837e70908652bac520e0e75882a146654c78c4eaf66f41ef4b4779',
      lineCount: 8337,
      uniqueTriggerCount: 37,
      rawTriggerHits: 240,
      programUnitCount: 16,
    },
  },
  USER: {
    baseTable: 'DATAK',
    tables: [
    'DATAK',
    'DATA_MH',
    'FB',
    'TITL',
    'USER_U',
  ],
    calledForms: [
    'USE_GN',
    'USE_MH',
  ],
    reports: [],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
    'KEY-DOWN',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/DATAK',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/USER/screen.json`,
      sourcePath: 'form/user.fmb',
      sourceSha256: '6493c0fb14414d4dd86d852c14c2028dd056260943292884592208e4d512e003',
      lineCount: 3923,
      uniqueTriggerCount: 19,
      rawTriggerHits: 118,
      programUnitCount: 5,
    },
  },
  DATA_AML: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'AMLH',
    'ATMMY',
    'ATMY',
    'DATAK',
    'DATA_ACM',
    'FBMY',
    'FBVF_Y',
    'FBY',
    'FMMY',
    'FMVFT_Y',
    'FMVF_Y',
    'FMY',
    'USERGN',
  ],
    calledForms: [],
    reports: [],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/DATA_AML/screen.json`,
      sourcePath: 'form/data_aml.fmb',
      sourceSha256: 'ce6b80a9869c41bc5d9325b7603a25205b2bb5c89f22340db5fc4152d11ba331',
      lineCount: 3943,
      uniqueTriggerCount: 23,
      rawTriggerHits: 102,
      programUnitCount: 7,
    },
  },
  RSEDIF: {
    baseTable: 'AKFA',
    tables: [
    'AKFA',
    'AMHSB',
    'AMLH',
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'KDAY',
    'MONTH',
    'RSIF',
    'RSIFF',
    'SCR',
    'TITL',
    'USERGN',
    'USER_U',
    'YEAR',
  ],
    calledForms: [],
    reports: [
    'RSEDIF',
  ],
    dbRoutines: [
    'MORNOM',
  ],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AKFA',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/RSEDIF/screen.json`,
      sourcePath: 'form/RSEDIF.fmb',
      sourceSha256: '097109e6dee6fc88db07d17aabddf8452a4cf4498995021eeedf2e67d9647c3e',
      lineCount: 6938,
      uniqueTriggerCount: 28,
      rawTriggerHits: 199,
      programUnitCount: 53,
    },
  },
  MRT: {
    baseTable: 'MRT',
    tables: [
    'DATAK',
    'DATA_ACM',
    'MRT',
    'USERGN',
    'USER_U',
  ],
    calledForms: [],
    reports: [],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
  ],
    coverageApi: [
      '/api/data/MRT',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/MRT/screen.json`,
      sourcePath: 'form/mrt.fmb',
      sourceSha256: '49dabc9776f9dafa7e597e9d8b6076b09b64b37e833c4c502c38814b6a7081f7',
      lineCount: 3537,
      uniqueTriggerCount: 23,
      rawTriggerHits: 97,
      programUnitCount: 6,
    },
  },
  AHTSAR: {
    baseTable: 'AHTSR',
    tables: [
    'AHTSR',
    'DATA_ACM',
    'USERGN',
  ],
    calledForms: [],
    reports: [
    'REPATH',
  ],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
    'KEY-COMMIT',
    'KEY-CREREC',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
  ],
    coverageApi: [
      '/api/data/AHTSR',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/AHTSAR/screen.json`,
      sourcePath: 'form/ahtsar.fmb',
      sourceSha256: '6c9ac5509fb415eca8df10b33a1c47245ac160effdf457782328aa43a04b1c9f',
      lineCount: 3142,
      uniqueTriggerCount: 18,
      rawTriggerHits: 80,
      programUnitCount: 3,
    },
  },
  COPY: {
    baseTable: 'ARSHF',
    tables: [
    'ARSHF',
    'ATMM',
    'ATMMF',
    'DATAKSXY',
    'DATA_ACM',
    'TITL',
    'USERGN',
    'YEAR',
  ],
    calledForms: [],
    reports: [],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-DELREC',
    'KEY-ENTQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
  ],
    coverageApi: [
      '/api/data/ARSHF',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/COPY/screen.json`,
      sourcePath: 'form/copy.fmb',
      sourceSha256: '0848a10df105c65b7288490d94791ef98c5d8cb0aea1acb32b987d67879ae4e0',
      lineCount: 3260,
      uniqueTriggerCount: 18,
      rawTriggerHits: 75,
      programUnitCount: 3,
    },
  },
  INANOU: {
    baseTable: 'DATAK',
    tables: [
    'DATAK',
    'USEIN',
  ],
    calledForms: [],
    reports: [
    'TIM',
  ],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
    'KEY-DOWN',
    'KEY-EXIT',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/DATAK',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/INANOU/screen.json`,
      sourcePath: 'form/inanou.fmb',
      sourceSha256: 'ef42943f52ed3cdb7f3decbbcbf742499dc46c40f99d44d98c9d3fad19f16eaa',
      lineCount: 2312,
      uniqueTriggerCount: 9,
      rawTriggerHits: 55,
      programUnitCount: 3,
    },
  },
  TRHL: {
    baseTable: 'ATM',
    tables: [
    'ATM',
    'ATMM',
    'ATMMF',
    'DATAK',
    'DATA_ACM',
    'FB',
    'FBF',
    'FBM',
    'FBMF',
    'FM',
    'FMM',
    'FMMF',
    'FMMFY',
    'FMMY',
    'FMY',
    'MONTH',
    'SNDK',
    'TBTRHL',
    'USERGN',
  ],
    calledForms: [],
    reports: [],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/ATM',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/TRHL/screen.json`,
      sourcePath: 'form/trhl.fmb',
      sourceSha256: '8d2a21abff7e98de4ad28c05f0d28bfc76662bd04f0806f38ee1ade6dd97dcd4',
      lineCount: 4137,
      uniqueTriggerCount: 30,
      rawTriggerHits: 120,
      programUnitCount: 6,
    },
  },
  TEL: {
    baseTable: 'AB',
    tables: [
    'AB',
    'ABF',
    'ABSNF',
    'AKFA',
    'AKFAF',
    'AKFAFS',
    'AKRANDH',
    'AMHSB',
    'AMHSBW',
    'AMLH',
    'ARD',
    'ARDF',
    'ARDT',
    'ARSHF',
    'ASHM_MSHM',
    'ASM',
    'ASMF',
    'ASSF',
    'ASSFB',
    'ATM',
    'ATMF',
    'ATMFY',
    'ATMM',
    'ATMMF',
    'ATMMFY',
    'ATMMY',
    'ATMT',
    'ATMY',
    'ATSF',
    'ATSFB',
    'BK',
    'BOFH',
    'BOFHF',
    'BOFHV',
    'BOFHVM',
    'BOFH_ALL',
    'BWT',
    'BWTF',
    'C_A',
    'DASOKA',
    'DASOKAD',
    'DASOKAM',
    'DASOKAMN',
    'DASOKB',
    'DASOKBN',
    'DATAFSOK',
    'DATAFSOKF',
    'DATAFSOKN',
    'DATAFSOKNF',
    'DATAFSOKT',
    'DATAK',
    'DATAKM',
    'DATAKMZ',
    'DATAKS',
    'DATAKSH',
    'DATAKSX',
    'DATAKSXY',
    'DATAKSX_Y',
    'DATAKSY',
    'DATAK_Q',
    'DATAK_SLF',
    'DATAK_Y',
    'DATAK_YY',
    'DATASOK',
    'DATASOKN',
    'DATA_AC',
    'DATA_ACM',
    'DATA_ACMB',
    'DATA_ACRA',
    'DATA_AG',
    'DATA_AGDD',
    'DATA_AGT',
    'DATA_AHD',
    'DATA_AHDF',
    'DATA_ALL',
    'DATA_ALLG',
    'DATA_ALLG1',
    'DATA_ALLGZ',
    'DATA_ALLZ',
    'DATA_BL',
    'DATA_BR1',
    'DATA_BR3',
    'DATA_BRF',
    'DATA_BRH',
    'DATA_BRHF',
    'DATA_BRK',
    'DATA_BRKF',
    'DATA_BRS',
    'DATA_BRT',
    'DATA_BRTF',
    'DATA_BRT_V_BRG',
    'DATA_BR_B',
    'DATA_BR_F',
    'DATA_BR_K',
    'DATA_FBTR',
    'DATA_FS',
    'DATA_GB',
    'DATA_GB2',
    'DATA_GB3',
    'DATA_HSL',
    'DATA_HSLB',
    'DATA_HSLM',
    'DATA_H_F_S',
    'DATA_KHM',
    'DATA_KHMF',
    'DATA_MH',
    'DATA_MSHM',
    'DATA_OD',
    'DATA_RNG',
    'DATA_RNGF',
    'DATA_SL',
    'DATA_SNR',
    'DATA_SNR_A',
    'DATA_THK',
    'DATA_THKF',
    'DATA_TM',
    'DATA_TM1',
    'DATA_W1',
    'DATA_W2',
    'DEUOUSER',
    'DEUOUSERF',
    'DFB',
    'DFBF',
    'DFBT',
    'DYDLAL',
    'DYDLALF',
    'EDDLIN',
    'FATAHD',
    'FATAML',
    'FATBT',
    'FATBT2',
    'FATBTF',
    'FATBTF2',
    'FB',
    'FBA',
    'FBF',
    'FBFA',
    'FBFH',
    'FBFY',
    'FBH',
    'FBM',
    'FBMF',
    'FBMFY',
    'FBMY',
    'FBT',
    'FBTR',
    'FBTRF',
    'FBV',
    'FBVF_Y',
    'FBVM',
    'FBY',
    'FHTBYH',
    'FHTBYHF',
    'FM',
    'FMD',
    'FMDY',
    'FMF',
    'FMFY',
    'FMM',
    'FMMF',
    'FMMFY',
    'FMMY',
    'FMT',
    'FMV',
    'FMVFT_Y',
    'FMVF_Y',
    'FMVM',
    'FMVT',
    'FMVTM',
    'FMY',
    'FTB',
    'GHWMT',
    'GNSH',
    'GRD',
    'GRDF',
    'GRP',
    'GRPG',
    'GRPK',
    'HD_HD',
    'HGROM',
    'HGROMB',
    'HMH',
    'HMHALL',
    'HWM',
    'HWMB',
    'IMP_MSHM',
    'KEYF',
    'KYDF_RMS',
    'KYDTF_RMS',
    'KYDT_RMS',
    'KYD_RMS',
    'K_B',
    'MEMO',
    'MHFD',
    'MKTBSRA',
    'MNAF',
    'MNTKA',
    'MODR',
    'MONT_C',
    'MRT',
    'MSHRI',
    'MSHRI2',
    'MSHRI3',
    'MSHRIF',
    'MZ',
    'MZT',
    'M_MB',
    'NAMER',
    'NKL_MSHM',
    'PARCOD',
    'PI_MS',
    'PSWDAR',
    'PSWDARN',
    'RG1',
    'RG2',
    'RIFM',
    'RIFMF',
    'RIFMFM',
    'RKHR',
    'RKHRS',
    'RSIF',
    'RSIFF',
    'RSIFFM',
    'RSIFF_MSHM',
    'RSIF_MSHM',
    'RSIF_SLL',
    'SARSH',
    'SARSHK',
    'SAR_FB',
    'SAR_H',
    'SCR',
    'SCRH',
    'SCRS',
    'SENDSMS',
    'SENDSMS_S',
    'SHM',
    'SKFM',
    'SMR',
    'SMRF',
    'SMRT',
    'SNDGAMD2',
    'SNDGAMD3',
    'SNDGAMD4',
    'SNDK',
    'SNDKD',
    'SNDKD2',
    'SNDKD22',
    'SNDKDF',
    'SNDKDF22',
    'SNDKF',
    'SNDK_MSHM',
    'SNDK_RMSH',
    'SNDK_T',
    'SNDS',
    'SNDSDAD',
    'SNDSDADM',
    'SNDSF',
    'SNDS_MSHM',
    'SNDS_RMSH',
    'SNF',
    'SNF1',
    'SNFB',
    'SNFROM',
    'SQUN',
    'SQUNS',
    'SUM_FBA',
    'SWDAR',
    'SWDARN',
    'SWDARV',
    'SWDARVN',
    'SWT',
    'TABALL',
    'TAX',
    'TGROM',
    'TGROMB',
    'THKR',
    'TITL',
    'TITLM',
    'TITLX',
    'TITL_B',
    'TKH_MSHM',
    'TLB',
    'TM',
    'TMF',
    'TSEER',
    'TSEERR',
    'TSEERR_B',
    'TSHT',
    'TSM',
    'TSMF',
    'TSMK',
    'TSMKF',
    'TWDAR',
    'TWDARN',
    'TYPEMS',
    'TYPEMSR',
    'T_BRG',
    'T_HF',
    'T_HW',
    'T_T1',
    'T_T1M',
    'T_T1R',
    'T_TALL',
    'T_TAML',
    'USEIN',
    'USERGN',
    'USERGNB',
    'USER_U',
    'V_SNDK_MS1',
    'V_SNDK_MS2',
    'V_SNDS_MS1',
    'V_SNDS_MS2',
    'V_SNDS_RMSH',
    'WH',
    'YEAR',
    'YMSH',
  ],
    calledForms: [
    'EXNEW',
    'HD',
    'SH_MHZON',
  ],
    reports: [],
    dbRoutines: [
    'ADD_FAD',
    'AHD',
    'AL_RB_MS',
    'CABAH',
    'CABAH2',
    'CABAHMM',
    'CAMLH',
    'COD_SNF',
    'COD_SNF2',
    'COD_SNF3',
    'COLR',
    'C_GNSH',
    'DAY_C',
    'DAY_CN',
    'DAY_DN',
    'FREP',
    'FU_RNEW',
    'G_T_F',
    'HSNF',
    'INDATE',
    'KMHZNON',
    'KSOR',
    'KSOR2',
    'MAX_ABO',
    'MONT_NA',
    'MORNOM',
    'MTADDM',
    'NAME_AB',
    'NAME_GHSB',
    'NAME_HSB',
    'NAME_MRT',
    'NAME_SNF',
    'NA_NO_SK',
    'NA_NZIL',
    'NA_NZIL_N',
    'NO_GHSB',
    'NO_ROM',
    'NO_SONDOK',
    'RMZ_RMZ_N',
    'RSEDGRD',
    'RSEDNEW',
    'RSEDNEWZ',
    'RSEDSANDH',
    'RSEDSANDHR',
    'RSEDSNF',
    'RSEDSNFX',
    'RSEDSNFX2',
    'RSEDSNFX2_Y',
    'RSED_SMS',
    'RSH_SLL',
    'RSH_WM',
    'SARB_S',
    'SARSF2',
    'SHB_HGZX',
    'SQUNX',
    'TAHD',
    'TYPEMSC',
    'TY_CKH',
    'TY_HGZ',
    'T_GNS',
    'T_HWC',
    'YEARM',
  ],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-DELREC',
    'KEY-ENTQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
  ],
    coverageApi: [
      '/api/data/AB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/TEL/screen.json`,
      sourcePath: 'form/tel.fmb',
      sourceSha256: 'c099e743a213860eb4037161c66939ad570842069562e4dba896e71be3c78442',
      lineCount: 29734,
      uniqueTriggerCount: 17,
      rawTriggerHits: 75,
      programUnitCount: 306,
    },
  },
  AKFAL: {
    baseTable: 'ABSNF',
    tables: [
    'ABSNF',
    'AKFA',
    'AKFAF',
    'AKFAFS',
    'AKRANDH',
    'AMHSB',
    'AMLH',
    'ARD',
    'ARDF',
    'ARSHF',
    'ASM',
    'ASMF',
    'ASSF',
    'ASSFB',
    'ATM',
    'ATMF',
    'ATMFY',
    'ATMM',
    'ATMMF',
    'ATMMFY',
    'ATMMY',
    'ATMT',
    'ATMY',
    'ATSF',
    'ATSFB',
    'BOFH',
    'BOFHF',
    'BWT',
    'BWTF',
    'DASOKA',
    'DASOKAM',
    'DATAFSOK',
    'DATAFSOKF',
    'DATAFSOKN',
    'DATAFSOKNF',
    'DATAFSOKT',
    'DATAK',
    'DATAKM',
    'DATAKS',
    'DATAKSX',
    'DATAK_MSHM',
    'DATAK_Q',
    'DATAK_SLF',
    'DATASOK',
    'DATASOKN',
    'DATA_AC',
    'DATA_ACM',
    'DATA_AG',
    'DATA_AHD',
    'DATA_AHDF',
    'DATA_BL',
    'DATA_BRF',
    'DATA_BRH',
    'DATA_BRHF',
    'DATA_BRK',
    'DATA_BRKF',
    'DATA_BRS',
    'DATA_BRT',
    'DATA_BRTF',
    'DATA_BR_F',
    'DATA_BR_K',
    'DATA_GB',
    'DATA_GB2',
    'DATA_GB3',
    'DATA_HSL',
    'DATA_HSLB',
    'DATA_HSLM',
    'DATA_KHM',
    'DATA_KHMF',
    'DATA_MSHM',
    'DEUOUSER',
    'DEUOUSERF',
    'DFB',
    'DFBF',
    'DFBT',
    'DYDLAL',
    'DYDLALF',
    'FATBT',
    'FATBT2',
    'FATBTF',
    'FATBTF2',
    'FB',
    'FBA',
    'FBF',
    'FBFA',
    'FBFH',
    'FBFY',
    'FBH',
    'FBM',
    'FBMF',
    'FBMFY',
    'FBMY',
    'FBT',
    'FBTR',
    'FBTRF',
    'FBVF',
    'FBY',
    'FHTBYH',
    'FHTBYHF',
    'FM',
    'FMD',
    'FMF',
    'FMFY',
    'FMM',
    'FMMF',
    'FMMFY',
    'FMMY',
    'FMT',
    'FMVF',
    'FMVFT',
    'FMY',
    'GRD',
    'GRDF',
    'HGROM',
    'HGROMB',
    'HWM',
    'HWMB',
    'KDAY',
    'KYDF_RMS',
    'KYDTF_RMS',
    'KYDT_RMS',
    'KYD_RMS',
    'MONTH',
    'MRT',
    'MSHRI',
    'MSHRI2',
    'MSHRI3',
    'MSHRIF',
    'NAMER',
    'NKL_MSHM',
    'RIFM',
    'RIFMF',
    'RIFMFM',
    'RSIF',
    'RSIFF',
    'RSIFFM',
    'RSIFF_MSHM',
    'RSIF_MSHM',
    'RSIF_SLL',
    'SKFM',
    'SMR',
    'SMRF',
    'SMRT',
    'SNDGAMD2',
    'SNDGAMD3',
    'SNDGAMD4',
    'SNDK',
    'SNDK2',
    'SNDKD',
    'SNDKD2',
    'SNDKD22',
    'SNDKDF',
    'SNDKDF22',
    'SNDKF',
    'SNDK_MSHM',
    'SNDS',
    'SNDSDAD',
    'SNDSDADM',
    'SNDSF',
    'SNDS_MSHM',
    'SNDS_RMSH',
    'SQUN',
    'SWT',
    'TGROM',
    'TGROMB',
    'THKR',
    'TITL',
    'TM',
    'TMF',
    'TSHT',
    'TSM',
    'TSMF',
    'TSMK',
    'TSMKF',
    'USEIN',
    'USERGN',
    'YEAR',
  ],
    calledForms: [],
    reports: [
    'REPKM',
    'REPKM2',
  ],
    dbRoutines: [
    'CABAH',
    'CAMLH',
    'SQUNX',
  ],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/ABSNF',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/AKFAL/screen.json`,
      sourcePath: 'form/akfal.fmb',
      sourceSha256: 'bf320567af76c4bbb454d4b54f71046a496d9715f61d1b801ad7fa4f00e5313a',
      lineCount: 7807,
      uniqueTriggerCount: 24,
      rawTriggerHits: 115,
      programUnitCount: 15,
    },
  },
  KF: {
    baseTable: 'AHTSR',
    tables: [
    'AHTSR',
    'DATA_ACM',
    'USERGN',
  ],
    calledForms: [],
    reports: [],
    dbRoutines: [],
    lovs: [
    'NA2',
  ],
    legacyKeys: [
    'KEY-COMMIT',
    'KEY-CREREC',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
  ],
    coverageApi: [
      '/api/data/AHTSR',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/KF/screen.json`,
      sourcePath: 'form/KF.fmb',
      sourceSha256: 'c6173208e48067c996d89c014873f2a6dad14c28b18ca26be8a3a8eacdb1c791',
      lineCount: 3093,
      uniqueTriggerCount: 18,
      rawTriggerHits: 67,
      programUnitCount: 4,
    },
  },
  SMS: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'DATAFSOK',
    'DATAK',
    'DATAKS',
    'DATA_AC',
    'DATA_ACM',
    'DATA_MSHM',
    'FBVF',
    'SENDSMS',
    'SMSDATAK',
    'SNDK_MSHM',
    'TITL',
    'USERGN',
  ],
    calledForms: [],
    reports: [],
    dbRoutines: [
    'CAMLH',
    'NAME_HSB',
    'TYPEMSC',
  ],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-ENTQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/SMS/screen.json`,
      sourcePath: 'form/SMS.fmb',
      sourceSha256: '6aab1afb0f5db10f39d71e1d9d1aa4dfb3daef8c9d16f215147da032a0f567a9',
      lineCount: 6568,
      uniqueTriggerCount: 24,
      rawTriggerHits: 89,
      programUnitCount: 47,
    },
  },
  SMSN: {
    baseTable: 'DATAKS',
    tables: [
    'DATAKS',
    'DATA_AC',
    'DATA_ACM',
    'TITL',
    'USERGN',
  ],
    calledForms: [],
    reports: [
    'NOTLE',
  ],
    dbRoutines: [],
    lovs: [
    'ALL',
    'DLAL',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-LISTVAL',
    'KEY-MENU',
  ],
    coverageApi: [
      '/api/data/DATAKS',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/SMSN/screen.json`,
      sourcePath: 'form/SMSN.fmb',
      sourceSha256: '5856ed6da26ff6199a7cb6e709d4e0c5f3828f35707d6aa2802c449bba55b61c',
      lineCount: 2494,
      uniqueTriggerCount: 24,
      rawTriggerHits: 110,
      programUnitCount: 2,
    },
  },
  SYS_SMS: {
    baseTable: 'DATAFSOK',
    tables: [
    'DATAFSOK',
    'DATAK',
    'DATA_ACM',
    'SENDSMS_S',
    'SNDK',
    'TITL',
    'USERGN',
  ],
    calledForms: [
    'TRMENU',
  ],
    reports: [],
    dbRoutines: [],
    lovs: [
    'NAMM',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/DATAFSOK',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/SYS_SMS/screen.json`,
      sourcePath: 'form/SYS_SMS.fmb',
      sourceSha256: '9dd2b096314f683a68ec93acae1b7a4c142378ba8223d8d6332551da4a6ba26e',
      lineCount: 5307,
      uniqueTriggerCount: 29,
      rawTriggerHits: 151,
      programUnitCount: 8,
    },
  },
  MEMO: {
    baseTable: 'MEMO',
    tables: [
    'MEMO',
  ],
    calledForms: [],
    reports: [],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
    'KEY-COMMIT',
    'KEY-CREREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/MEMO',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/MEMO/screen.json`,
      sourcePath: 'form/memo.fmb',
      sourceSha256: 'ba4cee1b62c36957c0babab1204d63899542f74152a4f16a59a78ba6554fb490',
      lineCount: 2985,
      uniqueTriggerCount: 20,
      rawTriggerHits: 119,
      programUnitCount: 2,
    },
  },
  AKFA: {
    baseTable: 'AKFA',
    tables: [
    'AKFA',
    'AKFAF',
    'AKFAFS',
    'AMHSB',
    'AMLH',
    'DATAK',
    'DATAKS',
    'DATA_AC',
    'DATA_ACM',
    'KDAY',
    'MONTH',
    'MRT',
    'SNDK',
    'TITL',
    'USERGN',
    'USER_U',
    'YEAR',
  ],
    calledForms: [],
    reports: [
    'AKF',
  ],
    dbRoutines: [
    'SQUNX',
  ],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-DUPREC',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AKFA',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/AKFA/screen.json`,
      sourcePath: 'form/akfa.fmb',
      sourceSha256: 'efc9c8ac3636b86822075e11feca349bcd214058d956f349bd0ab8c4ac99c511',
      lineCount: 6858,
      uniqueTriggerCount: 33,
      rawTriggerHits: 171,
      programUnitCount: 14,
    },
  },
  REPSK: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'AMLH',
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'HMHALL',
    'SNDK',
    'SNDKF',
    'SNDS',
    'USERGN',
    'USER_U',
  ],
    calledForms: [],
    reports: [
    'SNDK',
    'SNDK2',
    'SNDK3',
    'SNDK3M',
    'SNDKALL',
  ],
    dbRoutines: [
    'CAMLH',
    'FREP',
  ],
    lovs: [
    'NA2',
    'NAM',
    'NAS',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-LISTVAL',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPSK/screen.json`,
      sourcePath: 'form/repsk.fmb',
      sourceSha256: 'f2b7606f7ab45721f70fe896b2253077c6cf1267386907305c7df603aaa7704d',
      lineCount: 7043,
      uniqueTriggerCount: 30,
      rawTriggerHits: 196,
      programUnitCount: 9,
    },
  },
  REPSS: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'AMLH',
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'HMHALL',
    'SNDS',
    'SNDSF',
    'USERGN',
    'USER_U',
  ],
    calledForms: [],
    reports: [
    'SNDS',
    'SNDS2',
    'SNDS3',
    'SNDS3M',
    'SNDSALL',
  ],
    dbRoutines: [
    'CAMLH',
    'FREP',
  ],
    lovs: [
    'NA2',
    'NAM',
    'NAS',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-LISTVAL',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPSS/screen.json`,
      sourcePath: 'form/repss.fmb',
      sourceSha256: '8992cd5f74093d4366f7156439f4e5522dfd2fe2482c7ebb35d2effc76d054ee',
      lineCount: 6379,
      uniqueTriggerCount: 31,
      rawTriggerHits: 221,
      programUnitCount: 8,
    },
  },
  REPKD: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'AMLH',
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'HMHALL',
    'SNDK',
    'SNDKDF',
    'USERGN',
  ],
    calledForms: [],
    reports: [
    'SNDKD',
  ],
    dbRoutines: [
    'FREP',
  ],
    lovs: [
    'NA2',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-LISTVAL',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPKD/screen.json`,
      sourcePath: 'form/REPKD.fmb',
      sourceSha256: '12676bc901ee701abc3392cd688f1b6f4e2c08eeb874731bd05f83f485b8ff5e',
      lineCount: 5842,
      uniqueTriggerCount: 35,
      rawTriggerHits: 229,
      programUnitCount: 10,
    },
  },
  REPKD2: {
    baseTable: 'AMHSB',
    tables: [
    'AMHSB',
    'AMLH',
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'HMHALL',
    'SNDK',
    'SNDKD2',
    'USERGN',
  ],
    calledForms: [],
    reports: [
    'SNDKD2',
    'SNDKD22',
  ],
    dbRoutines: [
    'FREP',
  ],
    lovs: [
    'NA2',
    'NAM',
  ],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-LISTVAL',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/AMHSB',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPKD2/screen.json`,
      sourcePath: 'form/REPKD2.fmb',
      sourceSha256: '8e97f7dcdfc62f938d1a31b1fd460bebe7891eaaa8098df676033aa2306bde85',
      lineCount: 8068,
      uniqueTriggerCount: 31,
      rawTriggerHits: 184,
      programUnitCount: 9,
    },
  },
  REPDAY: {
    baseTable: 'DATAK',
    tables: [
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'HMHALL',
    'MRT',
    'TYPEMS',
    'USERGN',
  ],
    calledForms: [],
    reports: [
    'REPDAY',
    'REPDAYS',
    'TYPEMS',
  ],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/DATAK',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPDAY/screen.json`,
      sourcePath: 'form/repday.fmb',
      sourceSha256: 'bc20e1802a820aca4dc5549749d650c127efc29b9524af9df76e7fee68565757',
      lineCount: 4172,
      uniqueTriggerCount: 25,
      rawTriggerHits: 110,
      programUnitCount: 4,
    },
  },
  REPMZN: {
    baseTable: 'DATAK',
    tables: [
    'DATAK',
    'DATAKMZ',
    'DATA_AC',
    'DATA_ACM',
    'DATA_ALLG',
    'DATA_AMR',
    'MRT',
    'USERGN',
    'YEAR',
  ],
    calledForms: [
    'HMZAN',
  ],
    reports: [],
    dbRoutines: [
    'CAMLH',
    'RSEDNEW',
    'RSEDNEWZ',
    'RSEDSANDHR',
  ],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/DATAK',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPMZN/screen.json`,
      sourcePath: 'form/REPMZN.fmb',
      sourceSha256: '7b5c1dd2847e7865f0e97f8ac393c7a60f5f4859745b995530c18d251ffc2e23',
      lineCount: 5456,
      uniqueTriggerCount: 27,
      rawTriggerHits: 166,
      programUnitCount: 5,
    },
  },
  REPRANDH: {
    baseTable: 'DATAK',
    tables: [
    'DATAK',
    'DATAKMZ',
    'DATA_ACM',
    'FB',
    'MRT',
    'USERGN',
    'YEAR',
  ],
    calledForms: [
    'REPRBN',
  ],
    reports: [
    'REPKROHX',
  ],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/DATAK',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPRANDH/screen.json`,
      sourcePath: 'form/reprandh.fmb',
      sourceSha256: '8233563d78c2ab4d979962fc3c9a698d163aa45f5aed902a191209bd8326e170',
      lineCount: 3888,
      uniqueTriggerCount: 28,
      rawTriggerHits: 145,
      programUnitCount: 3,
    },
  },
  REPMZNYH: {
    baseTable: 'DATAK',
    tables: [
    'DATAK',
    'DATAKMZ',
    'DATA_AC',
    'DATA_ACM',
    'MRT',
    'USERGN',
    'YEAR',
  ],
    calledForms: [],
    reports: [
    'REPKFROHM',
    'REPMZAN',
  ],
    dbRoutines: [],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/DATAK',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPMZNYH/screen.json`,
      sourcePath: 'form/REPMZNYH.fmb',
      sourceSha256: 'd5d71dfaf776c247f7316b48b01b0052aab592cd4fb284d208381656000b9575',
      lineCount: 4410,
      uniqueTriggerCount: 26,
      rawTriggerHits: 132,
      programUnitCount: 4,
    },
  },
  REPMEMO: {
    baseTable: 'DATAK',
    tables: [
    'DATAK',
    'DATA_AC',
    'DATA_ACM',
    'HMHALL',
    'MSHRIF',
    'TITLX',
    'TYPEMS',
    'USERGN',
  ],
    calledForms: [],
    reports: [
    'REPFMX2',
    'REPKAMFS',
    'REPKAMFSSX2',
    'REPSNDASH',
    'TYPEMS',
  ],
    dbRoutines: [
    'CAMLH',
    'FREP',
    'NAME_HSB',
  ],
    lovs: [],
    legacyKeys: [
    'KEY-CLRBLK',
    'KEY-CLRFRM',
    'KEY-CLRREC',
    'KEY-COMMIT',
    'KEY-CQUERY',
    'KEY-CREREC',
    'KEY-DELREC',
    'KEY-DOWN',
    'KEY-DUP-ITEM',
    'KEY-ENTQRY',
    'KEY-EXEQRY',
    'KEY-EXIT',
    'KEY-HELP',
    'KEY-MENU',
    'KEY-NEXT-ITEM',
    'KEY-SCRDOWN',
    'KEY-SCRUP',
    'KEY-UP',
  ],
    coverageApi: [
      '/api/data/DATAK',
    ],
    sourceMeta: {
      catalogPath: `${SOURCE_CATALOG}/screens/REPMEMO/screen.json`,
      sourcePath: 'form/repmemo.fmb',
      sourceSha256: 'b82bb63387fc9fe82e8af4406ddd02a74f352fc09208f2e97c01833a7dfe480b',
      lineCount: 6005,
      uniqueTriggerCount: 29,
      rawTriggerHits: 179,
      programUnitCount: 7,
    },
  },
};
